spring:
  application:
    name: articleApplication

  datasource:
    url: jdbc:postgresql://localhost:5432/test-database
    username: postgres
    password: Postgres1234567890

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  cache:
    type: caffeine
    cache-names: articleViews, articles
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=10m

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

  info:
    env:
      enabled: true

info:
  app:
    name: Article Service
    version: 1.0.0
    description: Service to manage articles with cached view counts

article:
  view:
    db-persist-threshold: 5
